version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './backend:/var/www/html'
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - app
    command: /bin/sh -c "yarn && yarn dev"

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - '8888:80'
    volumes:
      - './backend:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - app

  db:
    image: mariadb:10.11.4-jammy
    container_name: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: huzin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - './db-data:/var/lib/mysql'
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
    ports:
      - '8181:80'
    networks:
      - app

networks:
  app:
    driver: bridge
volumes:
  db-data:
